image: williamyeh/ansible:centos7

test:
  script:
    - if [ -f 'requirements.yml' ]; then yum -y install git && ansible-galaxy install -r requirements.yml; fi
    - ansible-playbook test.yml --syntax-check
    # - ansible-playbook test.yml --connection=local -vvv # no aws creds, should dry run i guess...
